### ISSUE TITLE
bug in humidity sensor type

### ISSUE THREAD

**Issue by pilotak** [adafruit/Adafruit_SHT4X#4]
https://github.com/adafruit/Adafruit_SHT4X/blob/b1e51348ffca00bd8970696a962a6cfd760e9b9d/Adafruit_SHT4x.cpp#L258

should be 

https://github.com/adafruit/Adafruit_Sensor/blob/9096b2965335b7373bd2380b765b740da71e2dda/Adafruit_Sensor.h#L64

**Comment by caternuson** [comment]
Thanks. Yep, looks like copy-paste issue. Would you be willing to make a pull request to fix?
