### ISSUE TITLE
How to select pins for SCL/SDA

### ISSUE THREAD

**Issue by krupis** [adafruit/Adafruit_SHT4X#6]
Hey. I have Adafruit SHT40 sensor and would like to use it for the ESP32-S3 board.
I have never seen a library that does not allow user to reconfigure the SCL/SDA pins.

How am I meant to use this library ? I have a custom ESP32 board and I have wired the SCL/SDA to GPIO1 and GPIO2 respectively

**Comment by ladyada** [comment]
see https://github.com/espressif/arduino-esp32/issues/3779

**Comment by krupis** [comment]
> see [espressif/arduino-esp32#3779](https://github.com/espressif/arduino-esp32/issues/3779)

Very nice. Appreciate your efforts on getting this implemented :)
